version: '3.7'

services:
    web:
        build: .
        container_name: 'django-container'
        # command: python /code/manage.py runserver 0.0.0.0:8000 --settings=${LOCAL_SETTINGS}urlshort.settings.local
        command: python /code/manage.py runserver 0.0.0.0:8000 --settings=${RUN_SETTING}
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
        networks:
            db_network:
        links:
            - db:db
    db:
        image: postgres:13.3
        volumes: 
            - postgres-data:/var/lib/postgresql/data
        ports:
            - '5432'
        environment:
            POSTGRES_USER: ${DBUSER} 
            POSTGRES_PASSWORD: ${DBPASS} 
            POSTGRES_DB: ${DBNAME} 
        networks:
            db_network:
volumes:
    postgres-data:

networks:
    db_network:
        driver: bridge