# Generated by Django 3.2.5 on 2021-07-18 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visited', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.URLField(max_length=500, unique=True)),
                ('original', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='URLVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('date_url_visited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_visit', to='short.datevisited')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_visit', to='short.url')),
            ],
        ),
        migrations.AddField(
            model_name='datevisited',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_date', to='short.url'),
        ),
    ]
